from pydantic import BaseModel, Field
from typing import List, Optional

# ==========================================
# 1. THE UNIVERSAL SCHEMA (Ingestion Output)
# ==========================================
class ShippingRecord(BaseModel):
    """
    The standard format every messy Excel row is converted into.
    Whether it's MSC, ZIM, or Hapag, the parser must output this exact shape.
    """
    shipping_line: str = Field(description="The carrier, e.g., 'MSC', 'ZIM'")
    vessel_name: Optional[str] = Field(default=None, description="Name of the arriving vessel")
    container_number: Optional[str] = Field(default=None, description="The container ID")
    bill_of_lading: Optional[str] = Field(default=None, description="The BL number")
    messy_party_name: str = Field(description="The raw, uncleaned name from the Consignee or Notify Party column")
    notify_party: Optional[str] = Field(default=None, description="The notify party name from the manifest")
    party_role: str = Field(description="Either 'Consignee', 'Notify Party', 'Salvaged Consignee', or 'Unknown'")
    port_of_discharge: Optional[str] = Field(default=None, description="The destination port where cargo is unloaded")
    eta: Optional[str] = Field(default=None, description="Estimated Time of Arrival at the discharge port")
    size: Optional[str] = Field(default=None, description="Container size")
    teu: Optional[str] = Field(default=None, description="Container TEU")

# ==========================================
# 2. THE LLM RESOLUTION MODELS
# ==========================================
class ResolutionCandidate(BaseModel):
    """
    Represents a single messy record and the top 5 master accounts 
    generated by our pre-filter (Stage 1) to be sent to the LLM.
    """
    messy_name: str
    candidate_master_names: List[str]

class LLMMatchDecision(BaseModel):
    """
    The STRICT output format we will force the LLM to return.
    This prevents the LLM from writing paragraphs and forces a clean API response.
    """
    original_messy_name: str = Field(description="The original messy name provided")
    matched: bool = Field(description="True if a valid match was found in the candidates, False otherwise")
    resolved_master_name: Optional[str] = Field(default=None, description="The exact matching name from the candidate list. Null if no match.")
    confidence_score: int = Field(ge=0, le=100, description="LLM confidence in the match from 0 to 100")
    reasoning: str = Field(description="A brief 1-sentence explanation of why it matched or didn't match.")

# ==========================================
# 3. THE FINAL REPORTING MODEL
# ==========================================
class AccountShipmentSummary(BaseModel):
    """
    The final grouped data structure passed to the email generator.
    Groups multiple incoming containers under one resolved Master Account.
    """
    master_account_name: str
    total_containers: int
    shipments: List[ShippingRecord]